openapi: 3.0.0
info:
  title: OpenTerps
  description: An Open API that contains information about terpenes, the effects,
    and the cannabis varieties that contain them.
  termsOfService: https://wayhigh.we.bs
  contact:
    email: benjamminredden@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.2
externalDocs:
  description: Find out more about OpenTerps
  url: https://wayhigh.we.bs
servers:
- url: https://virtserver.swaggerhub.com/CountryFriedCoders/OpenTerps/0.0.1
tags:
- name: cannabis
  description: The plant.
- name: terpene
  description: One of the most important parts of the cannabis plant.
- name: effect
  description: The effect of said terpenes.
- name: user
  description: The people who love the plant and contribute to this API.
paths:
  /terpene:
    put:
      tags:
      - terpene
      summary: Update an existing terpene
      description: Update terpene in the api
      operationId: updateTerpene
      requestBody:
        $ref: '#/components/requestBodies/Terpene'
      responses:
        "400":
          description: Invalid ID supplied
        "404":
          description: Terpene not found
        "405":
          description: Validation exception
    post:
      tags:
      - terpene
      summary: Add a new terpene to the api
      description: Add new terpene to the api
      operationId: addTerpene
      requestBody:
        $ref: '#/components/requestBodies/Terpene'
      responses:
        "405":
          description: Invalid input
  /terpene/findByEffect:
    get:
      tags:
      - terpene
      summary: Finds Terpenes by effect
      description: Multiple status values can be provided with comma separated strings
      operationId: findTerpenesByEffect
      parameters:
      - name: effect
        in: query
        description: Effect values that need to be considered for filter
        required: true
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Terpene'
                x-content-type: application/xml
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Terpene'
        "400":
          description: Invalid effect value
  /terpene/{terpeneId}:
    get:
      tags:
      - terpene
      summary: Find terpene by ID
      description: Returns a single terpene
      operationId: getTerpeneById
      parameters:
      - name: terpeneId
        in: path
        description: ID of terpene to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Terpene'
            application/json:
              schema:
                $ref: '#/components/schemas/Terpene'
        "400":
          description: Invalid ID supplied
        "404":
          description: Terpene not found
    post:
      tags:
      - terpene
      summary: Updates a terpene in the api
      description: Update a single terpene in the API
      operationId: updateTerpeneByID
      parameters:
      - name: terpeneId
        in: path
        description: ID of terpene that needs to be updated
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/body'
      responses:
        "405":
          description: Invalid input
    delete:
      tags:
      - terpene
      summary: Deletes a terpene
      description: Deletes a terpene from the API
      operationId: deleteTerpene
      parameters:
      - name: api_key
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: terpeneId
        in: path
        description: Terpene id to delete
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "400":
          description: Invalid ID supplied
        "404":
          description: Terpene not found
  /cannabis:
    put:
      tags:
      - cannabis
      summary: Update an existing cannabis strain
      description: Update cannabis strain in the api
      operationId: updateCannabisStrain
      requestBody:
        $ref: '#/components/requestBodies/Cannabis'
      responses:
        "400":
          description: Invalid ID supplied
        "404":
          description: Cannabis strain not found
        "405":
          description: Validation exception
    post:
      tags:
      - cannabis
      summary: Add a new cannabis strains to the api
      description: Add new cannabis strains to the api
      operationId: addCannabisStrain
      requestBody:
        $ref: '#/components/requestBodies/Cannabis'
      responses:
        "405":
          description: Invalid input
  /cannabis/findByTerpene:
    get:
      tags:
      - cannabis
      summary: Finds cannabis strains by terpene
      description: Multiple status values can be provided with comma separated strings
      operationId: findCannabisStrainsByTerpene
      parameters:
      - name: terpene
        in: query
        description: Terpene values that need to be considered for filter
        required: true
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cannabis'
                x-content-type: application/xml
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cannabis'
        "400":
          description: Invalid terpene value
  /cannabis/{cannabisId}:
    get:
      tags:
      - cannabis
      summary: Find cannabis strain by ID
      description: Returns a single cannabis strain
      operationId: getCannabisStrainById
      parameters:
      - name: cannabisId
        in: path
        description: ID of cannabis strain to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Cannabis'
            application/json:
              schema:
                $ref: '#/components/schemas/Cannabis'
        "400":
          description: Invalid ID supplied
        "404":
          description: Cannabis strain not found
    post:
      tags:
      - cannabis
      summary: Updates a cannabis strain in the api
      description: Update a single cannabis strain in the API
      operationId: updateCannabisStrainByID
      parameters:
      - name: cannabisId
        in: path
        description: ID of cannabis strain that needs to be updated
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/body_1'
      responses:
        "405":
          description: Invalid input
    delete:
      tags:
      - cannabis
      summary: Deletes a cannabis strain
      description: Deletes a cannabis strain from the API
      operationId: deleteCannabisStrain
      parameters:
      - name: api_key
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: cannabisId
        in: path
        description: Cannabis strain id to delete
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "400":
          description: Invalid ID supplied
        "404":
          description: Cannabis strain not found
  /effect:
    put:
      tags:
      - effect
      summary: Update an existing effect
      description: Update effect in the api
      operationId: updateEffect
      requestBody:
        $ref: '#/components/requestBodies/Effect'
      responses:
        "400":
          description: Invalid ID supplied
        "404":
          description: Effect not found
        "405":
          description: Validation exception
    post:
      tags:
      - effect
      summary: Add a new effect to the api
      description: Add new effect to the api
      operationId: addEffect
      requestBody:
        $ref: '#/components/requestBodies/Effect'
      responses:
        "405":
          description: Invalid input
  /effect/{effectId}:
    get:
      tags:
      - effect
      summary: Find effect by ID
      description: Returns a single effect
      operationId: getEffectById
      parameters:
      - name: effectId
        in: path
        description: ID of effect to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Effect'
            application/json:
              schema:
                $ref: '#/components/schemas/Effect'
        "400":
          description: Invalid ID supplied
        "404":
          description: Terpene not found
    post:
      tags:
      - effect
      summary: Updates a effect in the api
      description: Update a single effect in the API
      operationId: updateEffectByID
      parameters:
      - name: effectId
        in: path
        description: ID of effect that needs to be updated
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/body_2'
      responses:
        "405":
          description: Invalid input
    delete:
      tags:
      - effect
      summary: Deletes an effect
      description: Deletes an effect from the API
      operationId: deleteEffect
      parameters:
      - name: api_key
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: effectId
        in: path
        description: Effect id to delete
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "400":
          description: Invalid ID supplied
        "404":
          description: Effect not found
  /user:
    post:
      tags:
      - user
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createUser
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        default:
          description: successful operation
  /user/createWithArray:
    post:
      tags:
      - user
      summary: Creates list of users with given input array
      operationId: createUsersWithArrayInput
      requestBody:
        $ref: '#/components/requestBodies/UserArray'
      responses:
        default:
          description: successful operation
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        apiKey:
          type: string
      xml:
        name: User
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      example:
        name: name
        id: 6
      xml:
        name: Category
    Cannabis:
      type: object
      properties:
        id:
          type: integer
          format: int64
        strain:
          type: string
        terpenes:
          type: array
          xml:
            name: terpene
            wrapped: true
          items:
            $ref: '#/components/schemas/Terpene'
      example:
        strain: strain
        terpenes:
        - effects:
          - name: name
            id: 7
          - name: name
            id: 7
          tastes:
          - name: name
            id: 5
          - name: name
            id: 5
          smells:
          - name: name
            id: 5
          - name: name
            id: 5
          name: myrcene
          id: 0
          category:
            name: name
            id: 6
          strains:
          - name: name
            id: 2
          - name: name
            id: 2
          tags:
          - name: name
            id: 1
          - name: name
            id: 1
        - effects:
          - name: name
            id: 7
          - name: name
            id: 7
          tastes:
          - name: name
            id: 5
          - name: name
            id: 5
          smells:
          - name: name
            id: 5
          - name: name
            id: 5
          name: myrcene
          id: 0
          category:
            name: name
            id: 6
          strains:
          - name: name
            id: 2
          - name: name
            id: 2
          tags:
          - name: name
            id: 1
          - name: name
            id: 1
        id: 0
      xml:
        name: Cannabis
    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      example:
        name: name
        id: 1
      xml:
        name: Tag
    Effect:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      example:
        name: name
        id: 7
      xml:
        name: Effect
    Strain:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      example:
        name: name
        id: 2
      xml:
        name: Strain
    Taste:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      example:
        name: name
        id: 5
      xml:
        name: Taste
    Smell:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      example:
        name: name
        id: 5
      xml:
        name: Smell
    Terpene:
      required:
      - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        category:
          $ref: '#/components/schemas/Category'
        name:
          type: string
          example: myrcene
        tags:
          type: array
          xml:
            name: tag
            wrapped: true
          items:
            $ref: '#/components/schemas/Tag'
        tastes:
          type: array
          xml:
            name: taste
            wrapped: true
          items:
            $ref: '#/components/schemas/Taste'
        smells:
          type: array
          xml:
            name: smell
            wrapped: true
          items:
            $ref: '#/components/schemas/Smell'
        strains:
          type: array
          xml:
            name: strain
            wrapped: true
          items:
            $ref: '#/components/schemas/Strain'
        effects:
          type: array
          xml:
            name: effect
            wrapped: true
          items:
            $ref: '#/components/schemas/Effect'
      example:
        effects:
        - name: name
          id: 7
        - name: name
          id: 7
        tastes:
        - name: name
          id: 5
        - name: name
          id: 5
        smells:
        - name: name
          id: 5
        - name: name
          id: 5
        name: myrcene
        id: 0
        category:
          name: name
          id: 6
        strains:
        - name: name
          id: 2
        - name: name
          id: 2
        tags:
        - name: name
          id: 1
        - name: name
          id: 1
      xml:
        name: Terpene
    body:
      type: object
      properties:
        effects:
          type: string
          description: Updated effects of the terpene
    body_1:
      type: object
      properties:
        terpenes:
          type: array
          description: Updated terpenes of the cannabis strain
          items:
            $ref: '#/components/schemas/Terpene'
    body_2:
      type: object
      properties:
        effects:
          type: string
          description: Updated effect
  requestBodies:
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/User'
      required: true
    Terpene:
      description: Terpene object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Terpene'
        application/xml:
          schema:
            $ref: '#/components/schemas/Terpene'
      required: true
    Cannabis:
      description: Cannabis object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Cannabis'
        application/xml:
          schema:
            $ref: '#/components/schemas/Cannabis'
      required: true
    Effect:
      description: Effect object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Effect'
        application/xml:
          schema:
            $ref: '#/components/schemas/Effect'
      required: true
    Smell:
      description: Smell object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Smell'
        application/xml:
          schema:
            $ref: '#/components/schemas/Smell'
      required: true
    Taste:
      description: Taste object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Taste'
        application/xml:
          schema:
            $ref: '#/components/schemas/Taste'
    Strain:
      description: Strain object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Strain'
        application/xml:
          schema:
            $ref: '#/components/schemas/Strain'
    Category:
      description: Category object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Category'
        application/xml:
          schema:
            $ref: '#/components/schemas/Category'
    Tag:
      description: Tag object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Tag'
        application/xml:
          schema:
            $ref: '#/components/schemas/Tag'
